# ????????? ??????????? ? Postgres ? Docker
spring.datasource.url=jdbc:postgresql://localhost:5433/bank_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase
spring.liquibase.change-log=classpath:db/migration/db.migration-master.xml

app.crypto.card.secret=${APP_CRYPTO_CARD_SECRET:}

app.security.jwt.secret=${APP_JWT_SECRET:}
app.security.jwt.access-token-ttl-seconds=900

app.security.hsts.enabled=true

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false