# ????????? H2 (???? ? ??????????? ??????)
spring.datasource.url=jdbc:h2:mem:bank_db;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ??????? H2 (???????? ?? ?????? http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# Liquibase
spring.liquibase.change-log=classpath:db/migration/db.migration-master.xml

app.crypto.card.secret=${APP_CRYPTO_CARD_SECRET:}

app.security.jwt.secret=${APP_JWT_SECRET:}
app.security.jwt.access-token-ttl-seconds=900

app.security.hsts.enabled=false

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true